// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Door.proto

package grpc.caihts.doorcontrol;

public final class DoorControlServiceImpl {
  private DoorControlServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doorcontrol_LengthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doorcontrol_LengthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doorcontrol_ReplaceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doorcontrol_ReplaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doorcontrol_DoorControlRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doorcontrol_DoorControlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doorcontrol_MultiDoorControlRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doorcontrol_MultiDoorControlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doorcontrol_MultiMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doorcontrol_MultiMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doorcontrol_DoorControlResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doorcontrol_DoorControlResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doorcontrol_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doorcontrol_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doorcontrol_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doorcontrol_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nDoor.proto\022\013doorcontrol\" \n\016LengthRespo" +
      "nse\022\016\n\006length\030\001 \001(\005\",\n\016ReplaceRequest\022\014\n" +
      "\004text\030\001 \001(\t\022\014\n\004char\030\002 \001(\t\"!\n\022DoorControl" +
      "Request\022\013\n\003val\030\001 \001(\t\"\'\n\027MultiDoorControl" +
      "Request\022\014\n\004text\030\001 \003(\t\"L\n\023MultiMessageReq" +
      "uest\0225\n\014multirequest\030\001 \003(\0132\037.doorcontrol" +
      ".DoorControlRequest\"\"\n\023DoorControlRespon" +
      "se\022\013\n\003val\030\001 \001(\t\"\\\n\007Message\022)\n\006detail\030\001 \001" +
      "(\0162\031.doorcontrol.Message.Enum\"&\n\004Enum\022\013\n" +
      "\007UNKNOWN\020\000\022\007\n\003LOW\020\001\022\010\n\004HIGH\020\002\"\007\n\005Empty2\213" +
      "\003\n\022DoorControlService\022N\n\007reverse\022\037.doorc" +
      "ontrol.DoorControlRequest\032 .doorcontrol." +
      "DoorControlResponse\"\000\0223\n\005empty\022\024.doorcon" +
      "trol.Message\032\022.doorcontrol.Empty\"\000\022X\n\rre" +
      "verseStream\022\037.doorcontrol.DoorControlReq" +
      "uest\032 .doorcontrol.DoorControlResponse\"\000" +
      "(\0010\001\022H\n\006length\022\037.doorcontrol.DoorControl" +
      "Request\032\033.doorcontrol.LengthResponse(\001\022L" +
      "\n\005split\022\037.doorcontrol.DoorControlRequest" +
      "\032 .doorcontrol.DoorControlResponse0\001B3\n\027" +
      "grpc.caihts.doorcontrolB\026DoorControlServ" +
      "iceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_doorcontrol_LengthResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_doorcontrol_LengthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doorcontrol_LengthResponse_descriptor,
        new java.lang.String[] { "Length", });
    internal_static_doorcontrol_ReplaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_doorcontrol_ReplaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doorcontrol_ReplaceRequest_descriptor,
        new java.lang.String[] { "Text", "Char", });
    internal_static_doorcontrol_DoorControlRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_doorcontrol_DoorControlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doorcontrol_DoorControlRequest_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_doorcontrol_MultiDoorControlRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_doorcontrol_MultiDoorControlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doorcontrol_MultiDoorControlRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_doorcontrol_MultiMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_doorcontrol_MultiMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doorcontrol_MultiMessageRequest_descriptor,
        new java.lang.String[] { "Multirequest", });
    internal_static_doorcontrol_DoorControlResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_doorcontrol_DoorControlResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doorcontrol_DoorControlResponse_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_doorcontrol_Message_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_doorcontrol_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doorcontrol_Message_descriptor,
        new java.lang.String[] { "Detail", });
    internal_static_doorcontrol_Empty_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_doorcontrol_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doorcontrol_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
