// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Door.proto

package grpc.caihts.doorcontrol;

public interface DoorControlResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doorcontrol.DoorControlResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val = 1;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 1;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();
}
