// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TempSmart.proto

package grpc.caihts.temperaturecontrol;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperaturecontrol.Empty)
    com.google.protobuf.MessageOrBuilder {
}
