// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Door.proto

package grpc.caihts.doorcontrol;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doorcontrol.Empty)
    com.google.protobuf.MessageOrBuilder {
}
