// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Smart.proto

package grpc.caihts.lightcontrol;

public final class LightControlServiceImpl {
  private LightControlServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightcontrol_LightControlRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightcontrol_LightControlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightcontrol_LightControlReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightcontrol_LightControlReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Smart.proto\022\014lightcontrol\"#\n\023LightCont" +
      "rolRequest\022\014\n\004name\030\001 \001(\t\"$\n\021LightControl" +
      "Reply\022\017\n\007message\030\001 \001(\t2g\n\014LightControl\022W" +
      "\n\017SayLightControl\022!.lightcontrol.LightCo" +
      "ntrolRequest\032\037.lightcontrol.LightControl" +
      "Reply\"\000B5\n\030grpc.caihts.lightcontrolB\027Lig" +
      "htControlServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lightcontrol_LightControlRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lightcontrol_LightControlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightcontrol_LightControlRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_lightcontrol_LightControlReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lightcontrol_LightControlReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightcontrol_LightControlReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
