// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Smart.proto

package grpc.caihts.lightcontrol;

public interface LightControlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightcontrol.LightControlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
