// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Smart.proto

package grpc.caihts.lightcontrol;

public interface LightControlReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightcontrol.LightControlReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
