// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TempSmart.proto

package grpc.caihts.temperaturecontrol;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperaturecontrol.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.temperaturecontrol.Message.Enum detail = 1;</code>
   */
  int getDetailValue();
  /**
   * <code>.temperaturecontrol.Message.Enum detail = 1;</code>
   */
  grpc.caihts.temperaturecontrol.Message.Enum getDetail();
}
