// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Door.proto

package grpc.caihts.doorcontrol;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doorcontrol.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.doorcontrol.Message.Enum detail = 1;</code>
   */
  int getDetailValue();
  /**
   * <code>.doorcontrol.Message.Enum detail = 1;</code>
   */
  grpc.caihts.doorcontrol.Message.Enum getDetail();
}
