// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Door.proto

package grpc.caihts.doorcontrol;

public interface MultiMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doorcontrol.MultiMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * THIS IS THE RESPONSE OF A BIDIRECTION STREAM  
   * </pre>
   *
   * <code>repeated .doorcontrol.DoorControlRequest multirequest = 1;</code>
   */
  java.util.List<grpc.caihts.doorcontrol.DoorControlRequest> 
      getMultirequestList();
  /**
   * <pre>
   * THIS IS THE RESPONSE OF A BIDIRECTION STREAM  
   * </pre>
   *
   * <code>repeated .doorcontrol.DoorControlRequest multirequest = 1;</code>
   */
  grpc.caihts.doorcontrol.DoorControlRequest getMultirequest(int index);
  /**
   * <pre>
   * THIS IS THE RESPONSE OF A BIDIRECTION STREAM  
   * </pre>
   *
   * <code>repeated .doorcontrol.DoorControlRequest multirequest = 1;</code>
   */
  int getMultirequestCount();
  /**
   * <pre>
   * THIS IS THE RESPONSE OF A BIDIRECTION STREAM  
   * </pre>
   *
   * <code>repeated .doorcontrol.DoorControlRequest multirequest = 1;</code>
   */
  java.util.List<? extends grpc.caihts.doorcontrol.DoorControlRequestOrBuilder> 
      getMultirequestOrBuilderList();
  /**
   * <pre>
   * THIS IS THE RESPONSE OF A BIDIRECTION STREAM  
   * </pre>
   *
   * <code>repeated .doorcontrol.DoorControlRequest multirequest = 1;</code>
   */
  grpc.caihts.doorcontrol.DoorControlRequestOrBuilder getMultirequestOrBuilder(
      int index);
}
