// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TempSmart.proto

package grpc.caihts.temperaturecontrol;

public interface MultiMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperaturecontrol.MultiMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .temperaturecontrol.TemperatureControlRequest multirequest = 1;</code>
   */
  java.util.List<grpc.caihts.temperaturecontrol.TemperatureControlRequest> 
      getMultirequestList();
  /**
   * <code>repeated .temperaturecontrol.TemperatureControlRequest multirequest = 1;</code>
   */
  grpc.caihts.temperaturecontrol.TemperatureControlRequest getMultirequest(int index);
  /**
   * <code>repeated .temperaturecontrol.TemperatureControlRequest multirequest = 1;</code>
   */
  int getMultirequestCount();
  /**
   * <code>repeated .temperaturecontrol.TemperatureControlRequest multirequest = 1;</code>
   */
  java.util.List<? extends grpc.caihts.temperaturecontrol.TemperatureControlRequestOrBuilder> 
      getMultirequestOrBuilderList();
  /**
   * <code>repeated .temperaturecontrol.TemperatureControlRequest multirequest = 1;</code>
   */
  grpc.caihts.temperaturecontrol.TemperatureControlRequestOrBuilder getMultirequestOrBuilder(
      int index);
}
