// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Door.proto

package grpc.caihts.doorcontrol;

public interface MultiDoorControlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doorcontrol.MultiDoorControlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * THIS IS THE MOST IMPORTANT PART FOR A BI DIRECTION STREAMING
   * </pre>
   *
   * <code>repeated string text = 1;</code>
   */
  java.util.List<java.lang.String>
      getTextList();
  /**
   * <pre>
   * THIS IS THE MOST IMPORTANT PART FOR A BI DIRECTION STREAMING
   * </pre>
   *
   * <code>repeated string text = 1;</code>
   */
  int getTextCount();
  /**
   * <pre>
   * THIS IS THE MOST IMPORTANT PART FOR A BI DIRECTION STREAMING
   * </pre>
   *
   * <code>repeated string text = 1;</code>
   */
  java.lang.String getText(int index);
  /**
   * <pre>
   * THIS IS THE MOST IMPORTANT PART FOR A BI DIRECTION STREAMING
   * </pre>
   *
   * <code>repeated string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes(int index);
}
