// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TempSmart.proto

package grpc.caihts.temperaturecontrol;

public interface MultiTemperatureControlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperaturecontrol.MultiTemperatureControlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string text = 1;</code>
   */
  java.util.List<java.lang.String>
      getTextList();
  /**
   * <code>repeated string text = 1;</code>
   */
  int getTextCount();
  /**
   * <code>repeated string text = 1;</code>
   */
  java.lang.String getText(int index);
  /**
   * <code>repeated string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes(int index);
}
