// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Door.proto

package grpc.caihts.doorcontrol;

public interface ReplaceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doorcontrol.ReplaceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>string char = 2;</code>
   */
  java.lang.String getChar();
  /**
   * <code>string char = 2;</code>
   */
  com.google.protobuf.ByteString
      getCharBytes();
}
