// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TempSmart.proto

package grpc.caihts.temperaturecontrol;

public final class TempetureControlServiceImpl {
  private TempetureControlServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tempeturecontrol_LengthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tempeturecontrol_LengthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tempeturecontrol_ReplaceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tempeturecontrol_ReplaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tempeturecontrol_TempetureControlRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tempeturecontrol_TempetureControlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tempeturecontrol_MultiTempetureControlRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tempeturecontrol_MultiTempetureControlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tempeturecontrol_MultiMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tempeturecontrol_MultiMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tempeturecontrol_TempetureControlResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tempeturecontrol_TempetureControlResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tempeturecontrol_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tempeturecontrol_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tempeturecontrol_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tempeturecontrol_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017TempSmart.proto\022\020tempeturecontrol\" \n\016L" +
      "engthResponse\022\016\n\006length\030\001 \001(\005\",\n\016Replace" +
      "Request\022\014\n\004text\030\001 \001(\t\022\014\n\004char\030\002 \001(\t\"&\n\027T" +
      "empetureControlRequest\022\013\n\003val\030\001 \001(\t\",\n\034M" +
      "ultiTempetureControlRequest\022\014\n\004text\030\001 \003(" +
      "\t\"V\n\023MultiMessageRequest\022?\n\014multirequest" +
      "\030\001 \003(\0132).tempeturecontrol.TempetureContr" +
      "olRequest\"\'\n\030TempetureControlResponse\022\013\n" +
      "\003val\030\001 \001(\t\"a\n\007Message\022.\n\006detail\030\001 \001(\0162\036." +
      "tempeturecontrol.Message.Enum\"&\n\004Enum\022\013\n" +
      "\007UNKNOWN\020\000\022\007\n\003LOW\020\001\022\010\n\004HIGH\020\002\"\007\n\005Empty2\345" +
      "\003\n\027TempetureControlService\022b\n\007reverse\022)." +
      "tempeturecontrol.TempetureControlRequest" +
      "\032*.tempeturecontrol.TempetureControlResp" +
      "onse\"\000\022=\n\005empty\022\031.tempeturecontrol.Messa" +
      "ge\032\027.tempeturecontrol.Empty\"\000\022l\n\rreverse" +
      "Stream\022).tempeturecontrol.TempetureContr" +
      "olRequest\032*.tempeturecontrol.TempetureCo" +
      "ntrolResponse\"\000(\0010\001\022W\n\006length\022).tempetur" +
      "econtrol.TempetureControlRequest\032 .tempe" +
      "turecontrol.LengthResponse(\001\022`\n\005split\022)." +
      "tempeturecontrol.TempetureControlRequest" +
      "\032*.tempeturecontrol.TempetureControlResp" +
      "onse0\001B=\n\034grpc.caihts.tempeturecontrolB\033" +
      "TempetureControlServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tempeturecontrol_LengthResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tempeturecontrol_LengthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tempeturecontrol_LengthResponse_descriptor,
        new java.lang.String[] { "Length", });
    internal_static_tempeturecontrol_ReplaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tempeturecontrol_ReplaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tempeturecontrol_ReplaceRequest_descriptor,
        new java.lang.String[] { "Text", "Char", });
    internal_static_tempeturecontrol_TempetureControlRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tempeturecontrol_TempetureControlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tempeturecontrol_TempetureControlRequest_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_tempeturecontrol_MultiTempetureControlRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tempeturecontrol_MultiTempetureControlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tempeturecontrol_MultiTempetureControlRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_tempeturecontrol_MultiMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tempeturecontrol_MultiMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tempeturecontrol_MultiMessageRequest_descriptor,
        new java.lang.String[] { "Multirequest", });
    internal_static_tempeturecontrol_TempetureControlResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tempeturecontrol_TempetureControlResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tempeturecontrol_TempetureControlResponse_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_tempeturecontrol_Message_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_tempeturecontrol_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tempeturecontrol_Message_descriptor,
        new java.lang.String[] { "Detail", });
    internal_static_tempeturecontrol_Empty_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_tempeturecontrol_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tempeturecontrol_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
