// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TempSmart.proto

package grpc.caihts.temperaturecontrol;

public interface TempetureControlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tempeturecontrol.TempetureControlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val = 1;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 1;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();
}
